language: scala

scala:
  - 2.11.4
  - 2.10.4

branches:
  only:
    - master
    - 2.2

notifications:
  email:
    recipients:
      - hacker@zhuchenye.com

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8