language: scala

scala:
  - 2.11.1
  - 2.11.0
  - 2.10.4
  - 2.10.3
  - 2.10.2
  - 2.10.1
  - 2.10.0

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - hacker@zhuchenye.com

jdk:
  - openjdk7
  - oraclejdk7