language: scala

scala:
  - 2.11.6
  - 2.10.5

branches:
  only:
    - master
    - 2.2

notifications:
  email:
    recipients:
      - hacker@zhuchenye.com

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8